import clr
import System
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

def GetWorksetKind(workset):
	if workset.GetType().ToString() == "Autodesk.Revit.DB.Workset":
		return System.Enum.GetName(WorksetKind, workset.Kind)
	elif workset.GetType().ToString() == "archilab.Revit.Elements.Workset":
		return "Cannot retrieve the workset kind from a workset object generated by archi-lab nodes."
	else: return None

worksets = UnwrapElement(IN[0])

if isinstance(IN[0], list): OUT = [GetWorksetKind(x) for x in worksets]
else: OUT = GetWorksetKind(worksets)