name: Node improvements
description: Suggest improvements for *existing* Clockwork nodes
title: "[Wish] "
labels: ["Improvement"]
assignees:
  - andydandy74
body:
  - type: markdown
    attributes:
      value: |
        Use this issue template to suggest improvements for **existing** Clockwork nodes. Please search to see if an issue already exists for the feature you want to request.
  - type: input
    id: AffectedNode
    attributes:
      label: Affected node
      description: Which node would you like to see improved? If multiple nodes are affected, enter "Multiple".
    validations:
      required: true
  - type: textarea
    id: ProblemDescription
    attributes:
      label: Problem description
      description: What is the problem that needs solving? Describe the shortcoming of the node. Depending on the case, it will be helpful if you include screenshots, step-by-step instructions, a simplified Dynamo graph and/or a simplified Revit model.
    validations:
      required: true
  - type: textarea
    id: ExpectedBehaviour
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expect the node to do differently. Do you need an additional input, additional output ports or datatypes, ...?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report.
