name: New Nodes
description: Suggest *new* Clockwork nodes
title: "[Wish] "
labels: ["New Feature"]
assignees:
  - andydandy74
body:
  - type: markdown
    attributes:
      value: |
        Use this issue template to suggest **new** Clockwork nodes. Please search to see if an issue already exists for the feature you want to request.
  - type: textarea
    id: ProblemDescription
    attributes:
      label: Problem description
      description: What is the problem that needs solving? Depending on the case, it will be helpful if you include screenshots, step-by-step instructions, a simplified Dynamo graph and/or a simplified Revit model.
    validations:
      required: true
  - type: textarea
    id: ProposedSolution
    attributes:
      label: ProposedSolution
      description: How would you like to see it solved? Provide a clear and concise description of what the new node should do, including description of inputs and outputs.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report.
