import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

def WorksetKind(workset):
	if workset.GetType().ToString() == "Autodesk.Revit.DB.Workset":
		return str(workset.Kind)
	elif workset.GetType().ToString() == "archilab.Revit.Elements.Workset":
		return "Cannot retrieve the workset kind from a workset object generated by archi-lab nodes."
	else: return None

worksets = UnwrapElement(IN[0])

if isinstance(IN[0], list): OUT = [WorksetKind(x) for x in worksets]
else: OUT = WorksetKind(worksets)